# Generated by Django 5.1.1 on 2024-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_level', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
