# Generated by Django 5.1.1 on 2024-09-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0002_bloodpressurecheck_diabetescheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCareCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('normal', 'Normal'), ('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive')], max_length=20)),
                ('concerns', models.TextField()),
                ('check_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
