# Generated by Django 5.1.1 on 2024-09-29 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0005_alter_userprofile_mobile_alter_userprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(30, '30 Days'), (60, '60 Days')])),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'duration')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='diabeteschallengeimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='diabeteschallengeimage',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ashaapp1.diabeteschallenge'),
        ),
        migrations.AlterUniqueTogether(
            name='diabeteschallengeimage',
            unique_together={('challenge', 'day')},
        ),
        migrations.RemoveField(
            model_name='diabeteschallengeimage',
            name='user',
        ),
    ]
