# Generated by Django 5.1.1 on 2024-10-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
