# Generated by Django 3.2.1 on 2024-10-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashaapp1', '0014_auto_20241014_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurechallengeimage',
            name='image',
            field=models.ImageField(upload_to='bloodpressure_challenge/'),
        ),
        migrations.AlterField(
            model_name='diabeteschallengeimage',
            name='image',
            field=models.ImageField(upload_to='diabetes_challenge/'),
        ),
    ]
